services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file: ../.env
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    container_name: backend
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db




